# Generated by Django 6.0.3 on 2026-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_enter',
            field=models.BooleanField(default=False),
        ),
    ]
